extends:
  - eslint:recommended
  - airbnb-base
env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
  no-console: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
