name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: multiple host
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: sasha
            key: ${{ secrets.PRIVATE_KEY }}
            script: |
                whoami
                ls -al
